# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_altavista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Motocicleta'), ('BICICLETA', 'Bicicleta'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app_altavista.propietario', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['propietario', 'tipo', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='PersonalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='Documento de identidad')),
                ('tipo_servicio', models.CharField(choices=[('DOMESTICO', 'Servicio Doméstico'), ('CONDUCTOR', 'Conductor'), ('JARDINERO', 'Jardinero'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de servicio')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_servicio', to='app_altavista.propietario', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Personal de Servicio',
                'verbose_name_plural': 'Personal de Servicio',
                'ordering': ['propietario', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('parentesco', models.CharField(choices=[('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('OTRO', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('documento_identidad', models.CharField(max_length=20, unique=True, verbose_name='Documento de identidad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_familiares', to='app_altavista.propietario', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Miembro Familiar',
                'verbose_name_plural': 'Miembros Familiares',
                'ordering': ['propietario', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de mascota')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='app_altavista.propietario', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['propietario', 'tipo', 'nombre'],
            },
        ),
        migrations.RenameField(
            model_name='propietariovivienda',
            old_name='fecha_adquisicion',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='propietariovivienda',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietariovivienda',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='propietariovivienda',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='propietariovivienda',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la ocupación o propiedad', verbose_name='Observaciones'),
        ),
    ]